---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "44"
year: "2023"
contributor: "Philipp Falkenburg"
title: "Praxisbericht institutionalisiertes Grassroots Open Access : Beitrag der Vernetzungs- und Kompetenzstelle Open Access Brandenburg (VuK) zum Open Access Tracking Project (OATP) "
pdf: "main.pdf"
date: 2023-12-19
comments: false
sharing: true
footer: true

---