---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "44"
year: "2023"
contributor: 
- Tobias Steiner
title: "<q>Alte Traditionen</q>: zur Rolle von scholar-led publishing und Open Access in den Geistes- und Sozialwissenschaften"
abstract: "Der vorliegende Beitrag beleuchtet den Ansatz des scholar-led publishing und zeigt auf, welche Zusammenhänge zwischen scholar-led Initiativen und der <q>klassischen</q> Open Access-Bewegung bestehen. Nach einer kurzen Diskurseinordnung leitet der Beitrag diachron ab, wie scholar-led Initiativen aus den Geistes- und Sozialwissenschaften schon früh und parallel zu den weithin rezipierten Entwicklungen aus dem medizinisch-naturwissenschaftlichen Bereich der 1990er Jahre auf eigene Weise wichtige Impulse zur Öffnung von Publikationskulturen setzten. Dazu werden exemplarisch eine Vielzahl von medien- und kulturwissenschaftlichen scholar-led Journals, Buchverlagen sowie weiterreichenden Netzwerk- und Infrastruktur-Initiativen entlang der größeren Entwicklungen der letzten vier Jahrzehnte hin zur Digitalisierung von wissenschaftlichen Publikationspraktiken und dem sich daraus ergebenden Potential eines alternativen Publikationssystems, welches gemeinschaftliche Kollaboration unter den Vorzeichen von Gemeinnützigkeit über kommerzorientierten Wettbewerb stellt."
pdf: "main.pdf"
date: 2023-12-22
comments: false
sharing: true
footer: true

---