---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "44"
year: "2023"
contributor: 
- Redaktion LIBREAS
title: "Editorial #44: Grassroots Open Access"
pdf: "https://doi.org/10.18452/28260"
doi: "10.18452/28260"
date: 2023-12-20
comments: false
sharing: true
footer: true

---