---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "44"
year: "2023"
contributor: 
- Redaktion LIBREAS
title: "Editorial #44: Grassroots Open Access"
pdf: main.pdf
date: 2023-12-20
comments: false
sharing: true
footer: true

---