---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "44"
year: "2023"
contributor: 
- Stefan Milius
- Wolfgang Thomas
title: "Logical Methods in Computer Science – Erfahrungsbericht über die Gründung einer internationalen Open-Access-Zeitschrift"
abstract: "<i>Logical Methods in Computer Science</i> ist eine wissenschaftsgesteuerte Diamond-Open-Access-Zeitschrift im Gebiet der Theoretischen Informatik. Wir berichten über die Entwicklung der Zeitschrift seit ihrer Gründung in 2004 und stellen Herausforderungen und Erfolgsfaktoren dar."
abstractalt: "<i>Logical Method in Computer Science</i> is a scholar-led diamond open access journal in theoretical computer science. We report on the development of the journal since its foundation in 2004 and discuss challenges and success factors."
pdf: "https://doi.org/10.18452/28261"
doi: "10.18452/28261"
date: 2023-12-22
comments: false
sharing: true
footer: true

---
