---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "44"
year: "2023"
contributor: 
  - Christian Erlinger
  - Jens Bemme
title: "Kamptaler Sakrallandschaften im Wikiversum"
subtitle: "Edits mit Versionsgeschichte: Elementarteilchen offener Wissensproduktion am Beispiel eines Citizen Science-Projektes"
abstract: "Die Autoren skizzieren, dass insbesondere lokales und regionales Wissen mit Wikis entsteht und dauerhaft bleibt – als Regionalia in globalen offenen Linkzusammenhängen. <q>Grass Root Open Access</q> bedeutet nicht nur, Publikationen auf selbst gezimmerte Art und Weise frei und unter offener Lizenz zu publizieren (<q>I have published my pdf under a cc license on my personal website</q>). <q>Grass Root Open Science</q> bedeutet auch, den Inhalt, die Daten und Bilder -- das Wissen einer publizistischen Arbeit an sich frei, offen und reproduzierbar zu veröffentlichen. Am Beispiel der <q>Wikifizierung</q> einer gedruckten, heimatkundlichen Buchpublikation wird gezeigt, wie mit Graswurzelstrategien im Wikiversums Open Science entsteht.<br> Wir skizzieren einen solchen Prozess als 'linked open': Methoden und Effekte regionaler Datenpflege als demokratisierende Praxis mittels Citizen Science, mit Blick auf Technologien und Gemeinschaften. Potentiell beeinflussen wir mit offenen, wiki-basierten und damit dezentralen Wissenssystemen die Kalkulation und Rentabilität öffentlicher und quasi-öffentlicher Investitionen in Bildungsressourcen, Informationsinfrastrukturen, Forschung und Entwicklung."
pdf: "main.pdf"
date: 2023-12-19
comments: false
sharing: true
footer: true

---