---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "44"
year: "2023"
contributor: 
- "Redaktion LIBREAS"
title: "Das liest die LIBREAS, Nummer #13 (Herbst–Winter 2023)"
pdf: "https://doi.org/10.18452/28271"
doi: "10.18452/28271"
date: 2023-07-22
comments: false
sharing: true
footer: true

---