---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "44"
year: "2023"
contributor: 
  - Ben Kaden
  - Linda Freyberg
title: "Makerspaces und Library Labs in wissenschaftlichen Bibliotheken – zwischen physischem Raum und forschungsorientierter Ausrichtung"
pdf: "main.pdf"
date: 2023-12-19
comments: false
sharing: true
footer: true

---