---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "44"
year: "2023"
contributor: 
- "Vorstand LIBREAS-Verein"
title: "In eigener Sache: Bericht über die Aktivitäten des LIBREAS-Vereins 2022/2023"
pdf: "https://doi.org/10.18452/28270"
doi: "10.18452/28270"
date: 2023-12-22
comments: false
sharing: true
footer: true

---